# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
   
conda:
  environment: environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py  # This should point to your conf.py

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
