# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  builder: html
  configuration: docs/conf.py  # This should point to your conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - sudo apt-get update
    - sudo apt-get install -y pandoc  
    - pip install --upgrade pip setuptools wheel
    - pip install hatch
    - hatch run docs:build
