version: 2.1

orbs:
  python: circleci/python@2.0.3

workflows:
  pytest-all:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    resource_class: medium+
    docker:
      - image: jupyter/scipy-notebook:4d9c9bd9ced0
    steps:
      - checkout
      - run:
          name: Install tox
          command: pip install tox
      - run:
          name: Run Tests
          command: tox